name: flutter_base_page
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter:
  assets:
    - assets/amigo_pet.jpg
    - assets/pet_love.jpg
    - assets/banho.jpg
    - assets/logo.png
    - assets/veterinario.jpg
    - assets/osso.png
    - assets/adocao.jpg
    - assets/logo_texto.jpg
    - assets/vacina.png
    - assets/icons8-google-logo-48.png
    - assets/icons8-mac-os-50.png
